//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductUrl { get; set; }
        public string ProductCode { get; set; }
        public System.DateTime Timestamp { get; set; }

        public Product()
        {
            Timestamp = DateTime.Now;
        }
    }
}
